name: zego_uikit
description: A new Flutter package project.
version: 0.0.1
homepage: http://doc.oa.zego.im/en#14746

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  http: ^0.13.4
  permission_handler: ^10.0.0
  native_device_orientation: ^1.1.4
  flutter_screenutil: ^5.5.3+2
  wakelock: ^0.6.2
  statemachine: ^3.2.0
  flutter_vibrate: ^1.3.0
  audioplayers: ^1.0.1
  zego_express_engine: ^2.21.1
  zego_zim: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/audio/CallRing.wav

    - assets/icons/s1_ctrl_bar_camera_normal.png
    - assets/icons/s1_ctrl_bar_camera_off.png
    - assets/icons/s1_ctrl_bar_end.png
    - assets/icons/s1_ctrl_bar_flip_camera.png
    - assets/icons/s1_ctrl_bar_mic_normal.png
    - assets/icons/s1_ctrl_bar_mic_off.png
    - assets/icons/s1_ctrl_bar_more_checked.png
    - assets/icons/s1_ctrl_bar_more_normal.png
    - assets/icons/s1_ctrl_bar_speaker_normal.png
    - assets/icons/s1_ctrl_bar_speaker_off.png
    - assets/icons/s1_ctrl_bar_speaker_bluetooth.png
    - assets/icons/s2_ctrl_bar_camera_normal.png
    - assets/icons/s2_ctrl_bar_camera_off.png
    - assets/icons/s2_ctrl_bar_flip_camera.png
    - assets/icons/s2_ctrl_bar_end.png
    - assets/icons/s2_ctrl_bar_member_normal.png
    - assets/icons/s2_ctrl_bar_message_normal.png
    - assets/icons/s2_ctrl_bar_mic_normal.png
    - assets/icons/s2_ctrl_bar_mic_off.png
    - assets/icons/s2_ctrl_bar_more.png
    - assets/icons/s2_ctrl_bar_speaker_normal.png
    - assets/icons/s2_ctrl_bar_speaker_off.png
    - assets/icons/s2_ctrl_bar_speaker_bluetooth.png
    - assets/icons/video_view_camera_on.png
    - assets/icons/video_view_camera_off.png
    - assets/icons/video_view_mic_off.png
    - assets/icons/video_view_mic_on.png
    - assets/icons/video_view_mic_speaking.png
    - assets/icons/video_view_wifi.png
    - assets/icons/invite_voice.png
    - assets/icons/invite_video.png
    - assets/icons/invite_reject.png
    - assets/icons/invite_background.png
    - assets/icons/toolbar_bottom_video.png
    - assets/icons/toolbar_bottom_voice.png
    - assets/icons/toolbar_bottom_decline.png
    - assets/icons/toolbar_bottom_cancel.png
    - assets/icons/toolbar_bottom_cancel.png
    - assets/icons/toolbar_top_switch_camera.png
    - assets/icons/nav_close.png
    - assets/icons/chat.png
    - assets/icons/send_disable.png
    - assets/icons/send.png

    - assets/icons/2.0x/s1_ctrl_bar_camera_normal.png
    - assets/icons/2.0x/s1_ctrl_bar_camera_off.png
    - assets/icons/2.0x/s1_ctrl_bar_end.png
    - assets/icons/2.0x/s1_ctrl_bar_flip_camera.png
    - assets/icons/2.0x/s1_ctrl_bar_mic_normal.png
    - assets/icons/2.0x/s1_ctrl_bar_mic_off.png
    - assets/icons/2.0x/s1_ctrl_bar_more_checked.png
    - assets/icons/2.0x/s1_ctrl_bar_more_normal.png
    - assets/icons/2.0x/s1_ctrl_bar_speaker_normal.png
    - assets/icons/2.0x/s1_ctrl_bar_speaker_off.png
    - assets/icons/2.0x/s1_ctrl_bar_speaker_bluetooth.png
    - assets/icons/2.0x/s2_ctrl_bar_camera_normal.png
    - assets/icons/2.0x/s2_ctrl_bar_camera_off.png
    - assets/icons/2.0x/s2_ctrl_bar_flip_camera.png
    - assets/icons/2.0x/s2_ctrl_bar_end.png
    - assets/icons/2.0x/s2_ctrl_bar_member_normal.png
    - assets/icons/2.0x/s2_ctrl_bar_message_normal.png
    - assets/icons/2.0x/s2_ctrl_bar_mic_normal.png
    - assets/icons/2.0x/s2_ctrl_bar_mic_off.png
    - assets/icons/2.0x/s2_ctrl_bar_more.png
    - assets/icons/2.0x/s2_ctrl_bar_speaker_normal.png
    - assets/icons/2.0x/s2_ctrl_bar_speaker_off.png
    - assets/icons/2.0x/s2_ctrl_bar_speaker_bluetooth.png
    - assets/icons/2.0x/video_view_camera_on.png
    - assets/icons/2.0x/video_view_camera_off.png
    - assets/icons/2.0x/video_view_mic_off.png
    - assets/icons/2.0x/video_view_mic_on.png
    - assets/icons/2.0x/video_view_mic_speaking.png
    - assets/icons/2.0x/video_view_wifi.png
    - assets/icons/2.0x/invite_voice.png
    - assets/icons/2.0x/invite_video.png
    - assets/icons/2.0x/invite_reject.png
    - assets/icons/2.0x/invite_background.png
    - assets/icons/2.0x/toolbar_bottom_video.png
    - assets/icons/2.0x/toolbar_bottom_voice.png
    - assets/icons/2.0x/toolbar_bottom_decline.png
    - assets/icons/2.0x/toolbar_bottom_cancel.png
    - assets/icons/2.0x/toolbar_bottom_cancel.png
    - assets/icons/2.0x/toolbar_top_switch_camera.png
    - assets/icons/2.0x/nav_close.png
    - assets/icons/2.0x/chat.png
    - assets/icons/2.0x/send_disable.png
    - assets/icons/2.0x/send.png

    - assets/icons/3.0x/s1_ctrl_bar_camera_normal.png
    - assets/icons/3.0x/s1_ctrl_bar_camera_off.png
    - assets/icons/3.0x/s1_ctrl_bar_end.png
    - assets/icons/3.0x/s1_ctrl_bar_flip_camera.png
    - assets/icons/3.0x/s1_ctrl_bar_mic_normal.png
    - assets/icons/3.0x/s1_ctrl_bar_mic_off.png
    - assets/icons/3.0x/s1_ctrl_bar_more_checked.png
    - assets/icons/3.0x/s1_ctrl_bar_more_normal.png
    - assets/icons/3.0x/s1_ctrl_bar_speaker_normal.png
    - assets/icons/3.0x/s1_ctrl_bar_speaker_off.png
    - assets/icons/3.0x/s1_ctrl_bar_speaker_bluetooth.png
    - assets/icons/3.0x/s2_ctrl_bar_camera_normal.png
    - assets/icons/3.0x/s2_ctrl_bar_camera_off.png
    - assets/icons/3.0x/s2_ctrl_bar_flip_camera.png
    - assets/icons/3.0x/s2_ctrl_bar_end.png
    - assets/icons/3.0x/s2_ctrl_bar_member_normal.png
    - assets/icons/3.0x/s2_ctrl_bar_message_normal.png
    - assets/icons/3.0x/s2_ctrl_bar_mic_normal.png
    - assets/icons/3.0x/s2_ctrl_bar_mic_off.png
    - assets/icons/3.0x/s2_ctrl_bar_more.png
    - assets/icons/3.0x/s2_ctrl_bar_speaker_normal.png
    - assets/icons/3.0x/s2_ctrl_bar_speaker_off.png
    - assets/icons/3.0x/s2_ctrl_bar_speaker_bluetooth.png
    - assets/icons/3.0x/video_view_camera_on.png
    - assets/icons/3.0x/video_view_camera_off.png
    - assets/icons/3.0x/video_view_mic_off.png
    - assets/icons/3.0x/video_view_mic_on.png
    - assets/icons/3.0x/video_view_mic_speaking.png
    - assets/icons/3.0x/video_view_wifi.png
    - assets/icons/3.0x/invite_voice.png
    - assets/icons/3.0x/invite_video.png
    - assets/icons/3.0x/invite_reject.png
    - assets/icons/3.0x/invite_background.png
    - assets/icons/3.0x/toolbar_bottom_video.png
    - assets/icons/3.0x/toolbar_bottom_voice.png
    - assets/icons/3.0x/toolbar_bottom_decline.png
    - assets/icons/3.0x/toolbar_bottom_cancel.png
    - assets/icons/3.0x/toolbar_bottom_cancel.png
    - assets/icons/3.0x/toolbar_top_switch_camera.png
    - assets/icons/3.0x/nav_close.png
